### ISSUE TITLE
KiCAD 9.0 - Broke this plugin.

### ISSUE THREAD

**Issue by chironb** [30350n/pcb2blender#95]
Seems like there's a change in KiCAD 9.0 that broke this plugin. When I export PCBs I know worked in version 8.0 I now get this error: 

Traceback (most recent call last):

File
"C:\Users\micro\OneDrive\Documentos\KiCAD\9.0\3rdparty\plugins\com_github_30350n_pcb2blender\__init__.py", line 22, in 
Run 
export_pcb3d(dialog.file_picker.GetPath(), boarddefs)

File
"C:\Users\micro\OneDrive\Documentos\KiCAD\9.0\3rdparty\plugins\com_github_30350n_pcb2blender\export.py", line 83, in 
export_pcb3d
pcbnew.ExportVRML(wrl_path, 0.001, True, True, 
components_path, 0.0, 0.0)

TypeError: ExportVRML() missing 2 required positional 
arguments: 'aXRef' and 'aYRef'

**Comment by chironb** [comment]
Looks like they updated the exporter for VRML. The call is different now. I tried fixing it but I didn't manage to get it.

https://docs.kicad.org/doxygen/classEXPORTER__VRML.html

bool 	ExportVRML_File (PROJECT *aProject, wxString *aMessages, const wxString &aFullFileName, double aMMtoWRMLunit, bool aIncludeUnspecified, bool aIncludeDNP, bool aExport3DFiles, bool aUseRelativePaths, const wxString &a3D_Subdir, double aXRef, double aYRef)

**Comment by chironb** [comment]
This is what I tried but I give up out of frustration: 

    # pcbnew.ExportVRML(wrl_path, 0.001, True, True, components_path, 0.0, 0.0)


    # Import necessary modules
    import pcbnew
    import wx

    # Define your variables
    project = pcbnew.GetBoard()  # Get the current project object
    messages = ["fuck","shit"]               # Initialize messages object
    # wrl_path = "path/to/your/board.wrl"       # Path to the WRL file
    unit_conversion = 0.001                   # Unit conversion factor
    include_unspecified = True                # Include unspecified items
    include_dnp = True                        # Include items marked as DNP (Do Not Place)
    export_3d_files = True                    # Export 3D files
    use_relative_paths = True                 # Use relative paths
    # components_path = "path/to/components"    # Path to the components directory
    x_ref = 0.0                               # X reference coordinate
    y_ref = 0.0                               # Y reference coordinate

    # Call the ExportVRML_File function
    pcbnew.ExportVRML_File(project, messages, wrl_path, unit_conversion, include_unspecified, include_dnp, export_3d_files, use_relative_paths, components_path, x_ref, y_ref)

**Comment by 30350n** [comment]
This is a duplicate of #89 and has already been fixed in #90. There's just no KiCad 9 release yet.

**Comment by 30350n** [comment]
[v2.17](https://github.com/30350n/pcb2blender/releases/tag/v2.17-k9.0-b4.2lts) supports KiCad 9.0 now. It should also be available via the internal Plugin and Content Manager in the next few days.
